"""Infrastructure adapters behind project-owned contracts.

Exports are resolved lazily so Temporal workflow sandbox imports do not eagerly
load SQLAlchemy, pgvector, boto3, or other process-only infrastructure.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORTS: dict[str, tuple[str, str]] = {
    "B1_SHADOW_TABLES": ("food_agent.foundation.evidence_schema", "B1_SHADOW_TABLES"),
    "B1_SOURCE_BATCH_TABLES": (
        "food_agent.foundation.evidence_schema",
        "B1_SOURCE_BATCH_TABLES",
    ),
    "B2_QUERY_REUSE_TABLES": ("food_agent.foundation.evidence_schema", "B2_QUERY_REUSE_TABLES"),
    "B3_MEMORY_INDEXES": ("food_agent.foundation.memory_schema", "B3_MEMORY_INDEXES"),
    "B3_MEMORY_TABLES": ("food_agent.foundation.memory_schema", "B3_MEMORY_TABLES"),
    "Boto3ObjectStore": ("food_agent.foundation.object_store", "Boto3ObjectStore"),
    "CURRENT_SCHEMA_REVISION": (
        "food_agent.foundation.schema_authority",
        "CURRENT_SCHEMA_REVISION",
    ),
    "CURRENT_SCHEMA_SIGNATURE": (
        "food_agent.foundation.schema_authority",
        "CURRENT_SCHEMA_SIGNATURE",
    ),
    "DEFAULT_CURRENT_SCHEMA_SIGNATURE": (
        "food_agent.foundation.schema_authority",
        "DEFAULT_CURRENT_SCHEMA_SIGNATURE",
    ),
    "DEFAULT_N_MINUS_1_SCHEMA_SIGNATURE": (
        "food_agent.foundation.schema_authority",
        "DEFAULT_N_MINUS_1_SCHEMA_SIGNATURE",
    ),
    "DeterministicEvaluator": (
        "food_agent.foundation.evaluation",
        "DeterministicEvaluator",
    ),
    "EvidenceShadowConfigView": ("food_agent.foundation.config", "EvidenceShadowConfigView"),
    "EvidenceShadowTelemetry": ("food_agent.foundation.observability", "EvidenceShadowTelemetry"),
    "EXPECTED_SCHEMA_REVISION": (
        "food_agent.foundation.schema_authority",
        "EXPECTED_SCHEMA_REVISION",
    ),
    "LLMJudgeRunner": ("food_agent.foundation.evaluation", "LLMJudgeRunner"),
    "FoundationAdapterError": ("food_agent.foundation.failures", "FoundationAdapterError"),
    "LEGACY_METADATA": ("food_agent.foundation.legacy_schema", "LEGACY_METADATA"),
    "LEGACY_TABLES": ("food_agent.foundation.legacy_schema", "LEGACY_TABLES"),
    "MEMORY_METADATA": ("food_agent.foundation.memory_schema", "MEMORY_METADATA"),
    "ModelConfigView": ("food_agent.foundation.config", "ModelConfigView"),
    "N_MINUS_1_SCHEMA_REVISION": (
        "food_agent.foundation.schema_authority",
        "N_MINUS_1_SCHEMA_REVISION",
    ),
    "N_MINUS_1_SCHEMA_SIGNATURE": (
        "food_agent.foundation.schema_authority",
        "N_MINUS_1_SCHEMA_SIGNATURE",
    ),
    "ObjectStoreConfigView": ("food_agent.foundation.config", "ObjectStoreConfigView"),
    "ObservabilityBootstrap": ("food_agent.foundation.observability", "ObservabilityBootstrap"),
    "ObservabilityConfigView": ("food_agent.foundation.config", "ObservabilityConfigView"),
    "QueryReuseReadConfigView": (
        "food_agent.foundation.config",
        "QueryReuseReadConfigView",
    ),
    "PersonalizationCanaryConfigView": (
        "food_agent.foundation.config",
        "PersonalizationCanaryConfigView",
    ),
    "PersonalizationCanaryTelemetry": (
        "food_agent.foundation.observability",
        "PersonalizationCanaryTelemetry",
    ),
    "PREVIOUS_SCHEMA_REVISION": (
        "food_agent.foundation.schema_authority",
        "PREVIOUS_SCHEMA_REVISION",
    ),
    "RateLimitDecision": ("food_agent.foundation.redis", "RateLimitDecision"),
    "RedisConfigView": ("food_agent.foundation.config", "RedisConfigView"),
    "RedisEventBusAdapter": ("food_agent.foundation.redis", "RedisEventBusAdapter"),
    "RedisFixedWindowRateLimiter": ("food_agent.foundation.redis", "RedisFixedWindowRateLimiter"),
    "RedisHotStateContract": ("food_agent.foundation.redis", "RedisHotStateContract"),
    "RedisIdempotencyWindow": ("food_agent.foundation.redis", "RedisIdempotencyWindow"),
    "RedisReplayExpiredError": ("food_agent.foundation.redis", "RedisReplayExpiredError"),
    "RedisSessionWindow": ("food_agent.foundation.redis", "RedisSessionWindow"),
    "RedisStateStore": ("food_agent.foundation.redis", "RedisStateStore"),
    "RedisUserSessionWindow": ("food_agent.foundation.redis", "RedisUserSessionWindow"),
    "RefreshMediaTelemetry": ("food_agent.foundation.observability", "RefreshMediaTelemetry"),
    "RepositoryConfigView": ("food_agent.foundation.config", "RepositoryConfigView"),
    "RepositorySlot": ("food_agent.foundation.database", "RepositorySlot"),
    "SchemaDivergentError": (
        "food_agent.foundation.schema_authority",
        "SchemaDivergentError",
    ),
    "SchemaNotReadyError": (
        "food_agent.foundation.schema_authority",
        "SchemaNotReadyError",
    ),
    "SchemaProbeError": ("food_agent.foundation.schema_authority", "SchemaProbeError"),
    "SchemaProbeResult": ("food_agent.foundation.schema_authority", "SchemaProbeResult"),
    "SchemaSignature": ("food_agent.foundation.schema_authority", "SchemaSignature"),
    "SchemaState": ("food_agent.foundation.schema_authority", "SchemaState"),
    "SchemaStateProbeResult": (
        "food_agent.foundation.schema_authority",
        "SchemaStateProbeResult",
    ),
    "SHADOW_METADATA": ("food_agent.foundation.evidence_schema", "SHADOW_METADATA"),
    "SQLAlchemyDatabase": ("food_agent.foundation.database", "SQLAlchemyDatabase"),
    "SQLAlchemyUnitOfWork": ("food_agent.foundation.database", "SQLAlchemyUnitOfWork"),
    "TargetAdapterDisabled": ("food_agent.foundation.base", "TargetAdapterDisabled"),
    "TargetSettings": ("food_agent.foundation.config", "TargetSettings"),
    "TemporalActivityAdapter": ("food_agent.foundation.temporal", "TemporalActivityAdapter"),
    "TemporalConfigView": ("food_agent.foundation.config", "TemporalConfigView"),
    "TemporalTaskQueues": ("food_agent.foundation.temporal", "TemporalTaskQueues"),
    "TemporalWorkerQuota": ("food_agent.foundation.temporal", "TemporalWorkerQuota"),
    "TemporalWorkflowAdapter": ("food_agent.foundation.temporal", "TemporalWorkflowAdapter"),
    "build_temporal_media_worker": ("food_agent.foundation.temporal", "build_temporal_media_worker"),
    "build_temporal_refresh_worker": (
        "food_agent.foundation.temporal",
        "build_temporal_refresh_worker",
    ),
    "build_temporal_worker": ("food_agent.foundation.temporal", "build_temporal_worker"),
    "claim_events": ("food_agent.foundation.memory_schema", "claim_events"),
    "consent_events": ("food_agent.foundation.memory_schema", "consent_events"),
    "conversation_turns": ("food_agent.foundation.memory_schema", "conversation_turns"),
    "correlation_attributes": ("food_agent.foundation.observability", "correlation_attributes"),
    "create_redis_client": ("food_agent.foundation.redis", "create_redis_client"),
    "deterministic_workflow_input": (
        "food_agent.foundation.temporal",
        "deterministic_workflow_input",
    ),
    "foundation_error_from_exception": (
        "food_agent.foundation.failures",
        "foundation_error_from_exception",
    ),
    "foundation_failure_boundary": ("food_agent.foundation.failures", "foundation_failure_boundary"),
    "memory_events": ("food_agent.foundation.memory_schema", "memory_events"),
    "memory_records": ("food_agent.foundation.memory_schema", "memory_records"),
    "memory_summaries": ("food_agent.foundation.memory_schema", "memory_summaries"),
    "minio_s3_client_factory": ("food_agent.foundation.object_store", "minio_s3_client_factory"),
    "outbox": ("food_agent.foundation.memory_schema", "outbox"),
    "preference_snapshots": ("food_agent.foundation.memory_schema", "preference_snapshots"),
    "prometheus_labels": ("food_agent.foundation.observability", "prometheus_labels"),
    "redact_log_context": ("food_agent.foundation.observability", "redact_log_context"),
    "assert_postgres_schema_state": (
        "food_agent.foundation.schema_authority",
        "assert_postgres_schema_state",
    ),
    "probe_postgres_schema_state": (
        "food_agent.foundation.schema_authority",
        "probe_postgres_schema_state",
    ),
    "probe_schema_state": ("food_agent.foundation.schema_authority", "probe_schema_state"),
    "BoundedObservationExporter": (
        "food_agent.foundation.telemetry",
        "BoundedObservationExporter",
    ),
    "InMemoryObservationPort": (
        "food_agent.foundation.telemetry",
        "InMemoryObservationPort",
    ),
    "CapturingObservationBackend": (
        "food_agent.foundation.telemetry",
        "CapturingObservationBackend",
    ),
    "InMemoryObservationBackend": (
        "food_agent.foundation.telemetry",
        "InMemoryObservationBackend",
    ),
    "NoopObservationPort": ("food_agent.foundation.telemetry", "NoopObservationPort"),
    "PhoenixEvalGateway": ("food_agent.foundation.evaluation", "PhoenixEvalGateway"),
    "PhoenixEvaluationAdapter": (
        "food_agent.foundation.evaluation",
        "PhoenixEvaluationAdapter",
    ),
    "PhoenixEvaluationGateway": (
        "food_agent.foundation.evaluation",
        "PhoenixEvaluationGateway",
    ),
    "PhoenixGatewayError": (
        "food_agent.foundation.evaluation",
        "PhoenixGatewayError",
    ),
    "OpenTelemetryObservationPort": (
        "food_agent.foundation.telemetry",
        "OpenTelemetryObservationPort",
    ),
    "OTelObservationPort": ("food_agent.foundation.telemetry", "OTelObservationPort"),
    "OTLPObservationPort": ("food_agent.foundation.telemetry", "OTLPObservationPort"),
    "OTLPHTTPObservationBackend": (
        "food_agent.foundation.telemetry",
        "OTLPHTTPObservationBackend",
    ),
    "otel_events_total": ("food_agent.foundation.telemetry_metrics", "otel_events_total"),
    "otel_exporter_health": (
        "food_agent.foundation.telemetry_metrics",
        "otel_exporter_health",
    ),
    "otel_queue_size": ("food_agent.foundation.telemetry_metrics", "otel_queue_size"),
    "record_otel_event": (
        "food_agent.foundation.telemetry_metrics",
        "record_otel_event",
    ),
    "set_otel_health": ("food_agent.foundation.telemetry_metrics", "set_otel_health"),
    "ObservationExportError": (
        "food_agent.foundation.telemetry",
        "ObservationExportError",
    ),
    "build_observation_exporter": (
        "food_agent.foundation.telemetry",
        "build_observation_exporter",
    ),
    "build_evaluation_port": (
        "food_agent.foundation.evaluation",
        "build_evaluation_port",
    ),
    "opaque_digest": ("food_agent.foundation.telemetry", "opaque_digest"),
    "TraceContext": ("food_agent.foundation.telemetry", "TraceContext"),
    "current_trace_context": (
        "food_agent.foundation.telemetry",
        "current_trace_context",
    ),
    "extract_trace_context": (
        "food_agent.foundation.telemetry",
        "extract_trace_context",
    ),
    "inject_trace_context": (
        "food_agent.foundation.telemetry",
        "inject_trace_context",
    ),
    "new_trace_context": ("food_agent.foundation.telemetry", "new_trace_context"),
    "observation_context": (
        "food_agent.foundation.telemetry",
        "observation_context",
    ),
    "observed_operation": ("food_agent.foundation.telemetry", "observed_operation"),
    "evaluate_gate": ("food_agent.foundation.evaluation", "evaluate_gate"),
    "project_evaluation_dataset": (
        "food_agent.foundation.evaluation",
        "project_evaluation_dataset",
    ),
    "project_evaluation_run": (
        "food_agent.foundation.evaluation",
        "project_evaluation_run",
    ),
    "QualificationGateEvaluator": (
        "food_agent.foundation.evaluation",
        "QualificationGateEvaluator",
    ),
    "redact_telemetry": ("food_agent.foundation.telemetry", "redact_telemetry"),
    "scrub_otel_record": ("food_agent.foundation.telemetry", "scrub_otel_record"),
    "session_state": ("food_agent.foundation.memory_schema", "session_state"),
}

__all__ = [
    "Boto3ObjectStore",
    "CURRENT_SCHEMA_REVISION",
    "CURRENT_SCHEMA_SIGNATURE",
    "DEFAULT_CURRENT_SCHEMA_SIGNATURE",
    "DEFAULT_N_MINUS_1_SCHEMA_SIGNATURE",
    "DeterministicEvaluator",
    "B1_SHADOW_TABLES",
    "B1_SOURCE_BATCH_TABLES",
    "B2_QUERY_REUSE_TABLES",
    "B3_MEMORY_INDEXES",
    "B3_MEMORY_TABLES",
    "FoundationAdapterError",
    "MEMORY_METADATA",
    "LEGACY_METADATA",
    "LEGACY_TABLES",
    "EvidenceShadowTelemetry",
    "EXPECTED_SCHEMA_REVISION",
    "LLMJudgeRunner",
    "PersonalizationCanaryTelemetry",
    "RefreshMediaTelemetry",
    "EvidenceShadowConfigView",
    "ModelConfigView",
    "ObjectStoreConfigView",
    "N_MINUS_1_SCHEMA_REVISION",
    "N_MINUS_1_SCHEMA_SIGNATURE",
    "ObservabilityBootstrap",
    "ObservabilityConfigView",
    "QueryReuseReadConfigView",
    "PersonalizationCanaryConfigView",
    "PREVIOUS_SCHEMA_REVISION",
    "RateLimitDecision",
    "RedisConfigView",
    "RedisEventBusAdapter",
    "RedisFixedWindowRateLimiter",
    "RedisHotStateContract",
    "RedisIdempotencyWindow",
    "RedisReplayExpiredError",
    "RedisSessionWindow",
    "RedisStateStore",
    "RedisUserSessionWindow",
    "RepositoryConfigView",
    "RepositorySlot",
    "SchemaDivergentError",
    "SchemaNotReadyError",
    "SchemaProbeError",
    "SchemaProbeResult",
    "SchemaSignature",
    "SchemaState",
    "SchemaStateProbeResult",
    "SQLAlchemyDatabase",
    "SQLAlchemyUnitOfWork",
    "SHADOW_METADATA",
    "TargetAdapterDisabled",
    "TargetSettings",
    "TemporalActivityAdapter",
    "TemporalConfigView",
    "TemporalTaskQueues",
    "TemporalWorkerQuota",
    "TemporalWorkflowAdapter",
    "claim_events",
    "consent_events",
    "conversation_turns",
    "memory_events",
    "memory_records",
    "memory_summaries",
    "outbox",
    "preference_snapshots",
    "session_state",
    "build_temporal_worker",
    "build_temporal_media_worker",
    "build_temporal_refresh_worker",
    "correlation_attributes",
    "create_redis_client",
    "deterministic_workflow_input",
    "foundation_error_from_exception",
    "foundation_failure_boundary",
    "minio_s3_client_factory",
    "prometheus_labels",
    "redact_log_context",
    "assert_postgres_schema_state",
    "probe_postgres_schema_state",
    "probe_schema_state",
    "BoundedObservationExporter",
    "CapturingObservationBackend",
    "InMemoryObservationBackend",
    "InMemoryObservationPort",
    "NoopObservationPort",
    "PhoenixEvalGateway",
    "PhoenixEvaluationAdapter",
    "PhoenixEvaluationGateway",
    "PhoenixGatewayError",
    "OpenTelemetryObservationPort",
    "OTelObservationPort",
    "OTLPObservationPort",
    "OTLPHTTPObservationBackend",
    "otel_events_total",
    "otel_exporter_health",
    "otel_queue_size",
    "record_otel_event",
    "set_otel_health",
    "ObservationExportError",
    "build_observation_exporter",
    "build_evaluation_port",
    "opaque_digest",
    "TraceContext",
    "current_trace_context",
    "extract_trace_context",
    "inject_trace_context",
    "new_trace_context",
    "observation_context",
    "observed_operation",
    "evaluate_gate",
    "project_evaluation_dataset",
    "project_evaluation_run",
    "QualificationGateEvaluator",
    "redact_telemetry",
    "scrub_otel_record",
]


def __getattr__(name: str) -> Any:
    target = _EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attribute = target
    value = getattr(import_module(module_name), attribute)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
