"""Canonical single-Agent adaptive investigation runtime.

The package owns the production Plan -> Act -> Observe -> Critique loop.  The
deterministic comment-first workflow remains a separate compatibility module;
it is not imported by this package or used by the production composition root.
"""

from .critic import (
    AdaptiveCritic,
    Critic,
    CriticDecision,
    CritiqueResult,
    EvidenceCritique,
    ModelCritic,
    parse_critic_decision,
)
from .engine import (
    AdaptiveAgent,
    AdaptiveInvestigationAgent,
    AdaptiveInvestigationState,
    InvestigationLoop,
    InvestigationRequest,
    InvestigationResult,
    InvestigationRound,
    InvestigationState,
    InvestigationStatus,
    RollingInvestigationLoop,
)
from .planner import (
    ActionKind,
    ActionSpec,
    AdaptiveAction,
    AdaptivePlanner,
    DeterministicFakeModel,
    FakeModelPort,
    InvestigationAction,
    InvestigationPlan,
    ModelPlanner,
    ModelPort,
    PlanDecision,
    Planner,
    PlannerDecision,
    ScriptedModelPort,
    TypedAction,
    build_model_request,
    coerce_action,
    invoke_model,
    parse_planner_decision,
)
from .scheduler import (
    ActionExecutor,
    ActionObservation,
    ActionResult,
    ActionScheduler,
    ActionStatus,
    AdaptiveBudget,
    BoundedActionScheduler,
    BudgetUsage,
    DeterministicFakeTool,
    FakeToolPort,
    InvestigationBudget,
    InvestigationScheduler,
    InvestigationSchedulerState,
    RunBudget,
    SchedulerResult,
    SchedulerState,
    ScriptedToolPort,
    ToolPort,
    WaveResult,
)
from .telemetry import AdaptiveObservationRecorder, recorder_for

__all__ = [
    "ActionExecutor",
    "ActionKind",
    "ActionObservation",
    "ActionResult",
    "ActionScheduler",
    "ActionSpec",
    "ActionStatus",
    "AdaptiveAction",
    "AdaptiveAgent",
    "AdaptiveBudget",
    "AdaptiveCritic",
    "AdaptiveInvestigationAgent",
    "AdaptiveInvestigationState",
    "AdaptivePlanner",
    "BoundedActionScheduler",
    "BudgetUsage",
    "Critic",
    "CriticDecision",
    "CritiqueResult",
    "DeterministicFakeModel",
    "DeterministicFakeTool",
    "EvidenceCritique",
    "FakeModelPort",
    "FakeToolPort",
    "InvestigationAction",
    "InvestigationBudget",
    "InvestigationLoop",
    "InvestigationPlan",
    "InvestigationRequest",
    "InvestigationResult",
    "InvestigationRound",
    "InvestigationScheduler",
    "InvestigationSchedulerState",
    "InvestigationState",
    "InvestigationStatus",
    "ModelCritic",
    "ModelPlanner",
    "ModelPort",
    "PlanDecision",
    "Planner",
    "PlannerDecision",
    "RollingInvestigationLoop",
    "RunBudget",
    "SchedulerResult",
    "SchedulerState",
    "ScriptedModelPort",
    "ScriptedToolPort",
    "ToolPort",
    "TypedAction",
    "WaveResult",
    "AdaptiveObservationRecorder",
    "recorder_for",
    "build_model_request",
    "coerce_action",
    "invoke_model",
    "parse_critic_decision",
    "parse_planner_decision",
]
