"""JSON contract round-trip and mixed-version schema compatibility gates."""

from __future__ import annotations

import json
from collections.abc import Mapping
from enum import StrEnum
from typing import Any, cast

from pydantic import BaseModel, JsonValue

from .base import ContractModel

SchemaNode = Mapping[str, Any]


class CompatibilityIssueCode(StrEnum):
    """Stable structural break categories used by contract CI gates."""

    FIELD_REMOVED = "field_removed"
    REQUIRED_FIELD_REMOVED = "required_field_removed"
    REQUIRED_FIELD_ADDED = "required_field_added"
    FIELD_TYPE_CHANGED = "field_type_changed"
    ENUM_VALUES_REMOVED = "enum_values_removed"
    ENUM_VALUES_ADDED = "enum_values_added"
    ENUM_CONSTRAINT_ADDED = "enum_constraint_added"
    ENUM_CONSTRAINT_REMOVED = "enum_constraint_removed"
    VALIDATION_CONSTRAINT_CHANGED = "validation_constraint_changed"


class SchemaCompatibilityIssue(ContractModel):
    code: CompatibilityIssueCode
    path: str
    previous: JsonValue = None
    candidate: JsonValue = None


class SchemaCompatibilityReport(ContractModel):
    """A deterministic, serializable report for one previous/candidate pair."""

    issues: tuple[SchemaCompatibilityIssue, ...] = ()

    @property
    def compatible(self) -> bool:
        return not self.issues


def round_trip_contract[ContractT: BaseModel](value: ContractT) -> ContractT:
    """Serialize a contract with wire aliases and validate it as the same type."""

    model_type = cast(type[ContractT], type(value))
    return model_type.model_validate_json(value.model_dump_json(by_alias=True))


def compare_contract_models(
    previous: type[BaseModel], candidate: type[BaseModel]
) -> SchemaCompatibilityReport:
    """Compare schemas generated by two Pydantic contract model versions."""

    return compare_contract_schemas(
        previous.model_json_schema(),
        candidate.model_json_schema(),
    )


def compare_contract_schemas(
    previous: SchemaNode, candidate: SchemaNode
) -> SchemaCompatibilityReport:
    """Detect structural changes unsafe for mixed old/new producers and consumers.

    The gate intentionally accepts a new optional property. It rejects field removal,
    requiredness changes, type changes, and finite enum/const set changes. JSON Schema
    annotations such as title, description, examples, and defaults are non-structural.
    """

    issues: list[SchemaCompatibilityIssue] = []
    visited: set[tuple[int, int]] = set()
    _compare_nodes(previous, candidate, previous, candidate, "$", issues, visited)
    return SchemaCompatibilityReport(issues=tuple(issues))


def _compare_nodes(
    previous_node: SchemaNode,
    candidate_node: SchemaNode,
    previous_root: SchemaNode,
    candidate_root: SchemaNode,
    path: str,
    issues: list[SchemaCompatibilityIssue],
    visited: set[tuple[int, int]],
) -> None:
    visit_key = (id(previous_node), id(candidate_node))
    if visit_key in visited:
        return
    visited.add(visit_key)

    previous_resolved = _resolve_local_ref(previous_node, previous_root)
    candidate_resolved = _resolve_local_ref(candidate_node, candidate_root)

    previous_types = _type_signature(previous_resolved, previous_root)
    candidate_types = _type_signature(candidate_resolved, candidate_root)
    if previous_types != candidate_types:
        issues.append(
            SchemaCompatibilityIssue(
                code=CompatibilityIssueCode.FIELD_TYPE_CHANGED,
                path=path,
                previous=[cast(JsonValue, item) for item in sorted(previous_types)],
                candidate=[cast(JsonValue, item) for item in sorted(candidate_types)],
            )
        )
        return

    _compare_finite_values(
        previous_resolved,
        candidate_resolved,
        previous_root,
        candidate_root,
        path,
        issues,
    )
    _compare_validation_constraints(
        previous_resolved,
        candidate_resolved,
        previous_root,
        candidate_root,
        path,
        issues,
        visited,
    )

    if "object" in previous_types:
        _compare_object_fields(
            previous_resolved,
            candidate_resolved,
            previous_root,
            candidate_root,
            path,
            issues,
            visited,
        )
    if "array" in previous_types:
        previous_items = previous_resolved.get("items")
        candidate_items = candidate_resolved.get("items")
        if isinstance(previous_items, Mapping) and isinstance(candidate_items, Mapping):
            _compare_nodes(
                previous_items,
                candidate_items,
                previous_root,
                candidate_root,
                f"{path}[]",
                issues,
                visited,
            )
        elif previous_items != candidate_items:
            _add_constraint_issue(
                path=f"{path}.items",
                previous=previous_items,
                candidate=candidate_items,
                issues=issues,
            )


_VALIDATION_KEYWORDS = (
    "multipleOf",
    "maximum",
    "exclusiveMaximum",
    "minimum",
    "exclusiveMinimum",
    "maxLength",
    "minLength",
    "pattern",
    "format",
    "contentEncoding",
    "contentMediaType",
    "maxItems",
    "minItems",
    "uniqueItems",
    "contains",
    "minContains",
    "maxContains",
    "prefixItems",
    "unevaluatedItems",
    "maxProperties",
    "minProperties",
    "additionalProperties",
    "unevaluatedProperties",
    "propertyNames",
    "patternProperties",
    "dependentRequired",
    "dependentSchemas",
    "anyOf",
    "oneOf",
    "allOf",
    "not",
    "if",
    "then",
    "else",
    "$dynamicRef",
)
_MISSING = object()
_ANNOTATION_KEYWORDS = frozenset(
    {
        "$comment",
        "default",
        "deprecated",
        "description",
        "examples",
        "readOnly",
        "title",
        "writeOnly",
    }
)
_UNORDERED_SCHEMA_ARRAY_KEYWORDS = frozenset({"allOf", "anyOf", "oneOf"})


def _compare_validation_constraints(
    previous: SchemaNode,
    candidate: SchemaNode,
    previous_root: SchemaNode,
    candidate_root: SchemaNode,
    path: str,
    issues: list[SchemaCompatibilityIssue],
    visited: set[tuple[int, int]],
) -> None:
    for keyword in _VALIDATION_KEYWORDS:
        previous_value = previous.get(keyword, _MISSING)
        candidate_value = candidate.get(keyword, _MISSING)
        if previous_value is _MISSING and candidate_value is _MISSING:
            continue
        if (
            keyword in {"anyOf", "oneOf"}
            and isinstance(previous_value, list)
            and isinstance(candidate_value, list)
            and _union_branches_are_compatible(
                previous_value,
                candidate_value,
                previous_root,
                candidate_root,
                visited,
            )
        ):
            continue
        if (
            previous_value is not _MISSING
            and candidate_value is not _MISSING
            and _normalize_schema_value(
                previous_value,
                previous_root,
                unordered=keyword in _UNORDERED_SCHEMA_ARRAY_KEYWORDS,
            )
            == _normalize_schema_value(
                candidate_value,
                candidate_root,
                unordered=keyword in _UNORDERED_SCHEMA_ARRAY_KEYWORDS,
            )
        ):
            continue
        _add_constraint_issue(
            path=f"{path}.{keyword}",
            previous=previous_value,
            candidate=candidate_value,
            issues=issues,
        )


def _union_branches_are_compatible(
    previous: list[object],
    candidate: list[object],
    previous_root: SchemaNode,
    candidate_root: SchemaNode,
    visited: set[tuple[int, int]],
) -> bool:
    """Match reordered union branches while preserving optional-field evolution."""

    if len(previous) != len(candidate):
        return False
    if not all(isinstance(branch, Mapping) for branch in (*previous, *candidate)):
        return False

    compatible_candidates: list[list[int]] = []
    for previous_branch in previous:
        matches: list[int] = []
        for candidate_index, candidate_branch in enumerate(candidate):
            branch_issues: list[SchemaCompatibilityIssue] = []
            _compare_nodes(
                cast(SchemaNode, previous_branch),
                cast(SchemaNode, candidate_branch),
                previous_root,
                candidate_root,
                "$union",
                branch_issues,
                set(visited),
            )
            if not branch_issues:
                matches.append(candidate_index)
        compatible_candidates.append(matches)

    matched_previous_by_candidate: dict[int, int] = {}

    def assign(previous_index: int, seen_candidates: set[int]) -> bool:
        for candidate_index in compatible_candidates[previous_index]:
            if candidate_index in seen_candidates:
                continue
            seen_candidates.add(candidate_index)
            current = matched_previous_by_candidate.get(candidate_index)
            if current is None or assign(current, seen_candidates):
                matched_previous_by_candidate[candidate_index] = previous_index
                return True
        return False

    return all(assign(index, set()) for index in range(len(previous)))


def _add_constraint_issue(
    *,
    path: str,
    previous: object,
    candidate: object,
    issues: list[SchemaCompatibilityIssue],
) -> None:
    issues.append(
        SchemaCompatibilityIssue(
            code=CompatibilityIssueCode.VALIDATION_CONSTRAINT_CHANGED,
            path=path,
            previous=None if previous is _MISSING else cast(JsonValue, previous),
            candidate=None if candidate is _MISSING else cast(JsonValue, candidate),
        )
    )


def _compare_object_fields(
    previous: SchemaNode,
    candidate: SchemaNode,
    previous_root: SchemaNode,
    candidate_root: SchemaNode,
    path: str,
    issues: list[SchemaCompatibilityIssue],
    visited: set[tuple[int, int]],
) -> None:
    previous_properties = _properties(previous)
    candidate_properties = _properties(candidate)
    previous_required = _required(previous)
    candidate_required = _required(candidate)

    for field_name in sorted(previous_properties.keys() - candidate_properties.keys()):
        code = (
            CompatibilityIssueCode.REQUIRED_FIELD_REMOVED
            if field_name in previous_required
            else CompatibilityIssueCode.FIELD_REMOVED
        )
        issues.append(
            SchemaCompatibilityIssue(
                code=code,
                path=_field_path(path, field_name),
                previous="required" if field_name in previous_required else "optional",
                candidate=None,
            )
        )

    for field_name in sorted(candidate_properties.keys() - previous_properties.keys()):
        if field_name in candidate_required:
            issues.append(
                SchemaCompatibilityIssue(
                    code=CompatibilityIssueCode.REQUIRED_FIELD_ADDED,
                    path=_field_path(path, field_name),
                    previous=None,
                    candidate="required",
                )
            )

    for field_name in sorted(previous_properties.keys() & candidate_properties.keys()):
        field_path = _field_path(path, field_name)
        was_required = field_name in previous_required
        is_required = field_name in candidate_required
        if was_required and not is_required:
            issues.append(
                SchemaCompatibilityIssue(
                    code=CompatibilityIssueCode.REQUIRED_FIELD_REMOVED,
                    path=field_path,
                    previous="required",
                    candidate="optional",
                )
            )
        elif not was_required and is_required:
            issues.append(
                SchemaCompatibilityIssue(
                    code=CompatibilityIssueCode.REQUIRED_FIELD_ADDED,
                    path=field_path,
                    previous="optional",
                    candidate="required",
                )
            )

        _compare_nodes(
            previous_properties[field_name],
            candidate_properties[field_name],
            previous_root,
            candidate_root,
            field_path,
            issues,
            visited,
        )


def _compare_finite_values(
    previous: SchemaNode,
    candidate: SchemaNode,
    previous_root: SchemaNode,
    candidate_root: SchemaNode,
    path: str,
    issues: list[SchemaCompatibilityIssue],
) -> None:
    previous_values = _finite_values(previous, previous_root)
    candidate_values = _finite_values(candidate, candidate_root)
    if previous_values is None and candidate_values is None:
        return
    if previous_values is None:
        issues.append(
            SchemaCompatibilityIssue(
                code=CompatibilityIssueCode.ENUM_CONSTRAINT_ADDED,
                path=path,
                previous=None,
                candidate=_ordered_values(candidate_values or {}),
            )
        )
        return
    if candidate_values is None:
        issues.append(
            SchemaCompatibilityIssue(
                code=CompatibilityIssueCode.ENUM_CONSTRAINT_REMOVED,
                path=path,
                previous=_ordered_values(previous_values),
                candidate=None,
            )
        )
        return

    removed = previous_values.keys() - candidate_values.keys()
    added = candidate_values.keys() - previous_values.keys()
    if removed:
        issues.append(
            SchemaCompatibilityIssue(
                code=CompatibilityIssueCode.ENUM_VALUES_REMOVED,
                path=path,
                previous=[previous_values[key] for key in sorted(removed)],
                candidate=None,
            )
        )
    if added:
        issues.append(
            SchemaCompatibilityIssue(
                code=CompatibilityIssueCode.ENUM_VALUES_ADDED,
                path=path,
                previous=None,
                candidate=[candidate_values[key] for key in sorted(added)],
            )
        )


def _resolve_local_ref(node: SchemaNode, root: SchemaNode) -> SchemaNode:
    resolved: SchemaNode = node
    seen: set[str] = set()
    while isinstance(resolved.get("$ref"), str):
        reference = cast(str, resolved["$ref"])
        if reference in seen or not reference.startswith("#/"):
            break
        seen.add(reference)
        target = _local_ref_target(reference, root)
        if target is None:
            return resolved
        siblings = {key: value for key, value in resolved.items() if key != "$ref"}
        resolved = {**target, **siblings}
    return resolved


def _local_ref_target(reference: str, root: SchemaNode) -> SchemaNode | None:
    if not reference.startswith("#/"):
        return None
    target: Any = root
    for raw_token in reference[2:].split("/"):
        token = raw_token.replace("~1", "/").replace("~0", "~")
        if not isinstance(target, Mapping) or token not in target:
            return None
        target = target[token]
    return target if isinstance(target, Mapping) else None


def _normalize_schema_value(
    value: object,
    root: SchemaNode,
    *,
    unordered: bool = False,
    active_refs: frozenset[str] = frozenset(),
) -> JsonValue:
    if isinstance(value, Mapping):
        reference = value.get("$ref")
        if isinstance(reference, str):
            target = _local_ref_target(reference, root)
            if target is not None:
                siblings = {key: item for key, item in value.items() if key != "$ref"}
                if reference in active_refs:
                    value = {"$recursiveRef": reference, **siblings}
                else:
                    return _normalize_schema_value(
                        {**target, **siblings},
                        root,
                        active_refs=active_refs | {reference},
                    )

        normalized: dict[str, JsonValue] = {}
        for key, item in sorted(value.items(), key=lambda pair: str(pair[0])):
            key_text = str(key)
            if key_text in _ANNOTATION_KEYWORDS or key_text == "$defs":
                continue
            normalized[key_text] = _normalize_schema_value(
                item,
                root,
                unordered=key_text in _UNORDERED_SCHEMA_ARRAY_KEYWORDS,
                active_refs=active_refs,
            )
        return normalized
    if isinstance(value, (list, tuple)):
        normalized_items = [
            _normalize_schema_value(item, root, active_refs=active_refs) for item in value
        ]
        if unordered:
            normalized_items.sort(key=_canonical_json)
        return normalized_items
    if value is None or isinstance(value, (bool, int, float, str)):
        return value
    return str(value)


def _type_signature(
    node: SchemaNode,
    root: SchemaNode,
    active_nodes: set[int] | None = None,
) -> frozenset[str]:
    stack = set() if active_nodes is None else active_nodes
    node_id = id(node)
    if node_id in stack:
        return frozenset({"unknown"})
    stack.add(node_id)
    try:
        resolved = _resolve_local_ref(node, root)
        for union_key in ("anyOf", "oneOf"):
            alternatives = resolved.get(union_key)
            if isinstance(alternatives, list):
                types: set[str] = set()
                for alternative in alternatives:
                    if isinstance(alternative, Mapping):
                        types.update(_type_signature(alternative, root, stack))
                return frozenset(types or {"unknown"})

        raw_type = resolved.get("type")
        if isinstance(raw_type, str):
            return frozenset({raw_type})
        if isinstance(raw_type, list) and all(isinstance(item, str) for item in raw_type):
            return frozenset(raw_type)
        if "const" in resolved:
            return frozenset({_json_type(resolved["const"])})
        if isinstance(resolved.get("enum"), list):
            return frozenset(_json_type(value) for value in resolved["enum"])
        if isinstance(resolved.get("properties"), Mapping):
            return frozenset({"object"})
        if "items" in resolved:
            return frozenset({"array"})
        return frozenset({"unknown"})
    finally:
        stack.remove(node_id)


def _finite_values(
    node: SchemaNode,
    root: SchemaNode,
    active_nodes: set[int] | None = None,
) -> dict[str, JsonValue] | None:
    stack = set() if active_nodes is None else active_nodes
    node_id = id(node)
    if node_id in stack:
        return None
    stack.add(node_id)
    try:
        resolved = _resolve_local_ref(node, root)
        if "const" in resolved:
            value = cast(JsonValue, resolved["const"])
            return {_canonical_json(value): value}
        enum_values = resolved.get("enum")
        if isinstance(enum_values, list):
            values = [cast(JsonValue, item) for item in enum_values]
            return {_canonical_json(value): value for value in values}

        for union_key in ("anyOf", "oneOf"):
            alternatives = resolved.get(union_key)
            if not isinstance(alternatives, list):
                continue
            combined: dict[str, JsonValue] = {}
            for alternative in alternatives:
                if not isinstance(alternative, Mapping):
                    return None
                alternative_values = _finite_values(alternative, root, stack)
                if alternative_values is None:
                    alternative_types = _type_signature(alternative, root)
                    if alternative_types == frozenset({"null"}):
                        alternative_values = {_canonical_json(None): None}
                    else:
                        return None
                combined.update(alternative_values)
            return combined
        return None
    finally:
        stack.remove(node_id)


def _properties(node: SchemaNode) -> dict[str, SchemaNode]:
    raw = node.get("properties")
    if not isinstance(raw, Mapping):
        return {}
    return {
        str(name): value
        for name, value in raw.items()
        if isinstance(value, Mapping)
    }


def _required(node: SchemaNode) -> set[str]:
    raw = node.get("required")
    if not isinstance(raw, list):
        return set()
    return {str(value) for value in raw}


def _field_path(parent: str, field_name: str) -> str:
    return f"{parent}.{field_name}"


def _ordered_values(values: dict[str, JsonValue]) -> list[JsonValue]:
    return [values[key] for key in sorted(values)]


def _canonical_json(value: JsonValue) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def _json_type(value: object) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, int):
        return "integer"
    if isinstance(value, float):
        return "number"
    if isinstance(value, str):
        return "string"
    if isinstance(value, list):
        return "array"
    if isinstance(value, dict):
        return "object"
    return "unknown"


__all__ = [
    "CompatibilityIssueCode",
    "SchemaCompatibilityIssue",
    "SchemaCompatibilityReport",
    "compare_contract_models",
    "compare_contract_schemas",
    "round_trip_contract",
]
