"""Infrastructure adapters behind project-owned contracts."""

from .base import TargetAdapterDisabled
from .config import (
    EvidenceShadowConfigView,
    ModelConfigView,
    ObjectStoreConfigView,
    ObservabilityConfigView,
    RedisConfigView,
    RepositoryConfigView,
    TargetSettings,
    TemporalConfigView,
)
from .database import RepositorySlot, SQLAlchemyDatabase, SQLAlchemyUnitOfWork
from .evidence_schema import B1_SHADOW_TABLES, B2_QUERY_REUSE_TABLES, SHADOW_METADATA
from .failures import (
    FoundationAdapterError,
    foundation_error_from_exception,
    foundation_failure_boundary,
)
from .memory_schema import (
    B3_MEMORY_INDEXES,
    B3_MEMORY_TABLES,
    MEMORY_METADATA,
    claim_events,
    consent_events,
    conversation_turns,
    memory_events,
    memory_records,
    memory_summaries,
    outbox,
    preference_snapshots,
    session_state,
)
from .object_store import Boto3ObjectStore, minio_s3_client_factory
from .observability import (
    EvidenceShadowTelemetry,
    ObservabilityBootstrap,
    correlation_attributes,
    prometheus_labels,
    redact_log_context,
)
from .redis import (
    RateLimitDecision,
    RedisEventBusAdapter,
    RedisFixedWindowRateLimiter,
    RedisHotStateContract,
    RedisIdempotencyWindow,
    RedisReplayExpiredError,
    RedisSessionWindow,
    RedisStateStore,
    RedisUserSessionWindow,
    create_redis_client,
)
from .temporal import (
    TemporalActivityAdapter,
    TemporalTaskQueues,
    TemporalWorkerQuota,
    TemporalWorkflowAdapter,
    build_temporal_worker,
    deterministic_workflow_input,
)

__all__ = [
    "Boto3ObjectStore",
    "B1_SHADOW_TABLES",
    "B2_QUERY_REUSE_TABLES",
    "B3_MEMORY_INDEXES",
    "B3_MEMORY_TABLES",
    "FoundationAdapterError",
    "MEMORY_METADATA",
    "EvidenceShadowTelemetry",
    "EvidenceShadowConfigView",
    "ModelConfigView",
    "ObjectStoreConfigView",
    "ObservabilityBootstrap",
    "ObservabilityConfigView",
    "RateLimitDecision",
    "RedisConfigView",
    "RedisEventBusAdapter",
    "RedisFixedWindowRateLimiter",
    "RedisHotStateContract",
    "RedisIdempotencyWindow",
    "RedisReplayExpiredError",
    "RedisSessionWindow",
    "RedisStateStore",
    "RedisUserSessionWindow",
    "RepositoryConfigView",
    "RepositorySlot",
    "SQLAlchemyDatabase",
    "SQLAlchemyUnitOfWork",
    "SHADOW_METADATA",
    "TargetAdapterDisabled",
    "TargetSettings",
    "TemporalActivityAdapter",
    "TemporalConfigView",
    "TemporalTaskQueues",
    "TemporalWorkerQuota",
    "TemporalWorkflowAdapter",
    "claim_events",
    "consent_events",
    "conversation_turns",
    "memory_events",
    "memory_records",
    "memory_summaries",
    "outbox",
    "preference_snapshots",
    "session_state",
    "build_temporal_worker",
    "correlation_attributes",
    "create_redis_client",
    "deterministic_workflow_input",
    "foundation_error_from_exception",
    "foundation_failure_boundary",
    "minio_s3_client_factory",
    "prometheus_labels",
    "redact_log_context",
]
