import type {
  UserResearchProjectionV1,
} from '../../../shared/contracts/research'
import { USER_RESEARCH_PROJECTION_SCHEMA_VERSION } from '../../../shared/contracts/research'

export const DEMO_CD_HOTPOT_PROJECTION: UserResearchProjectionV1 = {
  schemaVersion: USER_RESEARCH_PROJECTION_SCHEMA_VERSION,
  sessionId: 'session_demo_cd_hotpot',
  taskId: 'task_cd_hotpot_1',
  turnId: 1,
  runId: 'run_cd_hotpot',
  revision: 1,
  lastSequence: 4,
  status: 'succeeded',
  phase: 'completed',
  summary: `已为你深度穿透小红书（142篇本地笔记）与大众点评（1,890条真实消费评价）。
针对“成都玉林商圈、本地街坊高频复购、排队时间可控、牛油香醇不上火”的需求，严格过滤重度营销店，甄选出 3 家口碑极高的市井老店：

1. **青年火锅（玉林老店）**：二十年社区老店，牛油锅底厚重但回甘不燥，鲜鸭肠与千层肚每日屠场直供；
2. **绝城传统芋儿鸡火锅**：软糯脱骨芋儿与紧实跑山鸡绝配，辣度过瘾，本地老饕私藏避坑之选；
3. **鸿顺吉传统市井火锅**：巷子深处老味道，屠场鲜毛肚每桌必点，现炸花椒小酥肉酥脆正宗。`,
  intent: {
    objective: '成都玉林，本地人常去的老火锅，人均100，排队别太久，不要太甜太咸',
    location: '成都玉林',
    constraints: ['老火锅', '人均100', '免排队'],
    exclusions: ['重度营销店', '太甜太咸'],
  },
  plan: [
    {
      stepId: 'step_1',
      label: '意图拆解与偏好约束建模',
      status: 'succeeded',
      detail: '解析约束：商圈玉林、品类川味老火锅、人均100左右、严格控排队',
    },
    {
      stepId: 'step_2',
      label: '小红书真实口碑与踩坑笔记穿透',
      status: 'succeeded',
      detail: '提取 142 篇高赞素人避坑与复购笔记，剔除 38 篇疑似通投商业软文',
    },
    {
      stepId: 'step_3',
      label: '大众点评 POI 实体档案与均价核实',
      status: 'succeeded',
      detail: '匹配商户营业时段、排队等位波峰、人均消费 78-95 元真实核销记录',
    },
    {
      stepId: 'step_4',
      label: '多源证据交叉研判与避坑报告生成',
      status: 'succeeded',
      detail: '提炼 3 家入围老店、7 条核心评论证据与 2 个口味及等位争议焦点',
    },
  ],
  recommendations: [
    {
      recommendationId: 'rec_cd_1',
      title: '青年火锅（玉林老店）',
      summary: '玉林二十年市井老店，牛油锅底醇香浓郁，本地街坊回头客占比超 80%，鲜鸭肠与千层肚一绝。',
      rank: 1,
      confidence: 0.95,
      profileRef: 'prof_cd_1',
      highlights: ['鲜鸭肠每日现撕', '老成都醇香牛油越煮越香', '手工红糖糍粑外酥里嫩'],
      warnings: ['店内桌数仅14张，空间较拥挤', '18:00后排队超45分钟，建议17:30前到店'],
      evidenceRefs: ['ev_cd_1', 'ev_cd_2', 'ev_cd_3'],
      controversyRefs: ['ct_cd_1'],
    },
    {
      recommendationId: 'rec_cd_2',
      title: '绝城传统芋儿鸡火锅',
      summary: '软糯脱骨芋儿与紧实跑山鸡的经典结合，红油亮泽，辣而不燥，嗜辣老饕力荐。',
      rank: 2,
      confidence: 0.91,
      profileRef: 'prof_cd_2',
      highlights: ['芋儿入口即化', '鸡肉入味不柴', '秘制干碟回味微甘'],
      warnings: ['微辣对于不太能吃辣的朋友依然偏辣', '油碟偏重，建议搭配唯怡豆奶'],
      evidenceRefs: ['ev_cd_4', 'ev_cd_5'],
      controversyRefs: ['ct_cd_2'],
    },
    {
      recommendationId: 'rec_cd_3',
      title: '鸿顺吉传统市井火锅',
      summary: '巷子里开了十几年的老味道，屠场鲜毛肚每桌必点，现炸酥肉酥脆带花椒清香。',
      rank: 3,
      confidence: 0.88,
      profileRef: 'prof_cd_3',
      highlights: ['屠场直供鲜毛肚七上八下', '纯手工现炸花椒小酥肉', '冰粉解腻爽口'],
      warnings: ['老小区巷内停车极为不便，建议地铁芳草街站步行', '油烟味稍重'],
      evidenceRefs: ['ev_cd_6', 'ev_cd_7'],
      controversyRefs: [],
    },
  ],
  evidence: [
    {
      evidenceId: 'ev_cd_1',
      source: 'xhs_note',
      title: '吃了七年的玉林本地人真心话',
      excerpt: '青年火锅真的是我私藏食堂，锅底越煮越香但完全不锁喉，鸭肠和千层肚必点，就是千万别赶在饭点来，排到怀疑人生。',
      stance: 'positive',
      confidence: 0.96,
      capturedAt: '2026-03-08T19:22:00.000Z',
      noteRef: 'xhs_note_98124',
    },
    {
      evidenceId: 'ev_cd_2',
      source: 'dianping_review',
      title: '老居民真实探店评价',
      excerpt: '开了二十年了，环境虽然市井甚至有点挤，但底料确实没偷工减料，人均85吃得撑撑的，比春熙路那些网红店强十倍。',
      stance: 'positive',
      confidence: 0.93,
      capturedAt: '2026-03-05T20:11:00.000Z',
      commentRef: 'dp_rev_44120',
    },
    {
      evidenceId: 'ev_cd_3',
      source: 'xhs_note',
      title: '避坑提示：排队预警',
      excerpt: '五点半以后千万别来，堂子太小了只有十来张桌子，排号要等一个半小时以上，想吃必须五点一开门就冲！',
      stance: 'negative',
      confidence: 0.89,
      capturedAt: '2026-02-28T18:40:00.000Z',
      noteRef: 'xhs_note_87192',
    },
    {
      evidenceId: 'ev_cd_4',
      source: 'dianping_review',
      title: '芋儿鸡软糯脱骨',
      excerpt: '芋头炖得超级软糯，筷子一夹就化，鸡肉是跑山鸡很有嚼劲。我们三个人吃了两百四，性价比很高。',
      stance: 'positive',
      confidence: 0.94,
      capturedAt: '2026-03-01T13:15:00.000Z',
      commentRef: 'dp_rev_77312',
    },
    {
      evidenceId: 'ev_cd_5',
      source: 'xhs_note',
      title: '辣度警告与避坑说明',
      excerpt: '不能吃辣的朋友慎选！哪怕点微辣后劲都很足，不过配上冰汤圆和唯怡豆奶刚刚好。',
      stance: 'mixed',
      confidence: 0.87,
      capturedAt: '2026-03-04T21:05:00.000Z',
      noteRef: 'xhs_note_66541',
    },
    {
      evidenceId: 'ev_cd_6',
      source: 'dianping_review',
      title: '巷子里的老味道鲜毛肚',
      excerpt: '毛肚脆生生的，七上八下刚刚好。小酥肉是现炸的，带一点点花椒粒特别提味。',
      stance: 'positive',
      confidence: 0.91,
      capturedAt: '2026-02-20T18:50:00.000Z',
      commentRef: 'dp_rev_90214',
    },
    {
      evidenceId: 'ev_cd_7',
      source: 'xhs_note',
      title: '交通与环境说明',
      excerpt: '在老小区巷子里，车千万不要开进来，根本没地停！坐地铁8号线芳草街站出来走几分钟最方便。',
      stance: 'negative',
      confidence: 0.85,
      capturedAt: '2026-03-02T12:30:00.000Z',
      noteRef: 'xhs_note_33118',
    },
  ],
  controversies: [
    {
      controversyId: 'ct_cd_1',
      topic: '辣度与牛油厚重感争议',
      summary: '老食客赞赏牛油醇厚不寡淡，而初次品尝者反映吃到后半程略显油厚，对辣度耐受度要求高。',
      status: 'partially_resolved',
      sides: [
        {
          sideId: 's1',
          label: '重度嗜辣老饕',
          summary: '牛油锅底越煮越香，厚重挂汁，这才是地道老成都老火锅的风骨。',
          evidenceRefs: ['ev_cd_1', 'ev_cd_2'],
        },
        {
          sideId: 's2',
          label: '清淡/外地食客',
          summary: '后半程牛油容易凝固感增加，建议点微辣并加适量白菜降油。',
          evidenceRefs: ['ev_cd_5'],
        },
      ],
    },
    {
      controversyId: 'ct_cd_2',
      topic: '市井环境体验 vs 饭点等位忍耐度',
      summary: '高性价比与正宗味道受到普遍好评，但老店桌数少导致高峰期叫号等待时间偏长。',
      status: 'resolved',
      sides: [
        {
          sideId: 's1',
          label: '支持市井烟火气',
          summary: '老街坊巷子氛围很有味道，价格实惠食材新鲜。',
          evidenceRefs: ['ev_cd_2', 'ev_cd_4'],
        },
        {
          sideId: 's2',
          label: '建议错峰避免久等',
          summary: '18点之后等位时间容易超过40分钟，强烈建议错峰到店。',
          evidenceRefs: ['ev_cd_3', 'ev_cd_7'],
        },
      ],
    },
  ],
  profiles: [
    {
      profileId: 'prof_cd_1',
      name: '青年火锅（玉林老店）',
      rating: 4.7,
      reviewCount: 1420,
      averagePrice: 85,
      address: '成都市武侯区玉林西路165号附2号',
      openingHours: '周一至周日 11:30-14:00, 17:00-23:30',
      category: '川味老火锅',
      tags: ['玉林口碑榜', '本地街坊常去', '鲜鸭肠', '老牛油'],
      recommendedDishes: ['生抠鲜鸭肠', '鲜毛肚', '现炸酥肉', '手工红糖糍粑'],
    },
    {
      profileId: 'prof_cd_2',
      name: '绝城传统芋儿鸡火锅',
      rating: 4.6,
      reviewCount: 980,
      averagePrice: 78,
      address: '成都市武侯区芳草东街28号',
      openingHours: '周一至周日 11:00-22:00',
      category: '芋儿鸡 / 火锅',
      tags: ['软糯芋儿', '跑山鸡', '高性价比'],
      recommendedDishes: ['招牌芋儿鸡', '秘制干碟', '红糖冰汤圆', '时令青菜'],
    },
    {
      profileId: 'prof_cd_3',
      name: '鸿顺吉传统市井火锅',
      rating: 4.5,
      reviewCount: 760,
      averagePrice: 92,
      address: '成都市武侯区玉林中路38号院内',
      openingHours: '周一至周日 17:00-02:00',
      category: '市井老火锅',
      tags: ['深夜食堂', '屠场直供', '巷子深处'],
      recommendedDishes: ['屠场鲜毛肚', '花椒小酥肉', '老肉片', '千层肚'],
    },
  ],
  gaps: [],
  metrics: {
    rounds: 3,
    actions: 12,
    evidenceItems: 7,
    commentEvidenceItems: 7,
    profiles: 3,
    controversies: 2,
    gaps: 0,
  },
  updatedAt: new Date().toISOString(),
  appliedEventIds: ['ev_cd_1', 'ev_cd_2', 'ev_cd_3'],
}

export const DEMO_GZ_TEA_PROJECTION: UserResearchProjectionV1 = {
  schemaVersion: USER_RESEARCH_PROJECTION_SCHEMA_VERSION,
  sessionId: 'session_demo_gz_tea',
  taskId: 'task_gz_tea_1',
  turnId: 1,
  runId: 'run_gz_tea',
  revision: 1,
  lastSequence: 4,
  status: 'succeeded',
  phase: 'completed',
  summary: `针对“广州越秀或荔湾区正宗早茶，两人人均80，虾饺要扎实”的需求，已分析小红书 98 篇本地食客测评与大众点评 1,240 条食客评价：

甄选出 2 家传承传统手工手艺、本地街坊喝早茶的首选茶楼：
1. **荣华楼（百年老字号）**：越秀区老街坊最爱，纯手工三层大虾饺，虾肉爽脆弹牙，二楼早茶自带粤剧演出；
2. **源记传统茗茶居**：荔湾市井平价茶楼，两人人均75元即可品尝干蒸烧卖、豉汁排骨与陈皮牛肉丸。`,
  intent: {
    objective: '广州越秀或荔湾区正宗早茶，两人人均80，虾饺要扎实',
    location: '广州越秀/荔湾',
    constraints: ['广式早茶', '人均80', '手工虾饺'],
    exclusions: ['预制半成品'],
  },
  plan: [
    {
      stepId: 'step_gz_1',
      label: '传统老字号与现做点心筛选',
      status: 'succeeded',
      detail: '排除冷冻预制半成品茶楼，锁定越秀与荔湾老牌手工现包茶居',
    },
    {
      stepId: 'step_gz_2',
      label: '食客点评与虾饺品质比对',
      status: 'succeeded',
      detail: '深度比对虾仁用料新鲜度、澄粉皮厚度与折褶工艺',
    },
  ],
  recommendations: [
    {
      recommendationId: 'rec_gz_1',
      title: '荣华楼（百年老字号）',
      summary: '始于清末的老字号茶楼，点心老师傅现做现蒸，虾饺个头大、笋丝清甜爽口。',
      rank: 1,
      confidence: 0.94,
      profileRef: 'prof_gz_1',
      highlights: ['整颗鲜虾现包虾饺', '传统粤剧折子戏现场表演', '怀旧广式茶楼风情'],
      warnings: ['上午9:00前多为老街坊占座，建议8:30前或10:30后错峰到店'],
      evidenceRefs: ['ev_gz_1'],
      controversyRefs: [],
    },
    {
      recommendationId: 'rec_gz_2',
      title: '源记传统茗茶居',
      summary: '荔湾老城区高性价比茶居，平价大份，深受本地老街坊家庭聚会喜爱。',
      rank: 2,
      confidence: 0.90,
      profileRef: 'prof_gz_2',
      highlights: ['手工现捏干蒸烧卖', '豉汁蒸凤爪软烂脱骨', '传统陈皮牛肉丸'],
      warnings: ['无专属停车场，建议乘地铁1号线至陈家祠站步行'],
      evidenceRefs: ['ev_gz_2'],
      controversyRefs: [],
    },
  ],
  evidence: [
    {
      evidenceId: 'ev_gz_1',
      source: 'xhs_note',
      title: '老西关人的早茶白月光',
      excerpt: '荣华楼的虾饺真的顶，一口咬下去全是脆弹的虾仁，笋丁提鲜刚刚好，皮薄得透光却很有韧性。',
      stance: 'positive',
      confidence: 0.95,
      capturedAt: '2026-03-06T09:15:00.000Z',
      noteRef: 'xhs_gz_3312',
    },
    {
      evidenceId: 'ev_gz_2',
      source: 'dianping_review',
      title: '街坊早茶实惠之选',
      excerpt: '我和老伴每周都来，两人喝茶吃四屉点心才78块，比天河那些新派点心铺地道多了。',
      stance: 'positive',
      confidence: 0.91,
      capturedAt: '2026-03-03T10:20:00.000Z',
      commentRef: 'dp_gz_9941',
    },
  ],
  controversies: [],
  profiles: [
    {
      profileId: 'prof_gz_1',
      name: '荣华楼（百年老字号）',
      rating: 4.6,
      reviewCount: 2150,
      averagePrice: 82,
      address: '广州市越秀区龙津东路708号',
      openingHours: '周一至周日 07:00-14:30, 17:00-21:00',
      category: '粤菜早茶',
      tags: ['百年老店', '非遗手艺', '早茶粤曲'],
      recommendedDishes: ['荣华大虾饺', '豉汁蒸排骨', '蛋挞皇', '金牌红米肠'],
    },
    {
      profileId: 'prof_gz_2',
      name: '源记传统茗茶居',
      rating: 4.5,
      reviewCount: 890,
      averagePrice: 72,
      address: '广州市荔湾区宝华路122号',
      openingHours: '周一至周日 06:30-14:00',
      category: '广式茶居',
      tags: ['老西关', '高性价比', '街坊茶市'],
      recommendedDishes: ['招牌鲜虾烧卖', '豉汁蒸凤爪', '陈皮牛肉丸'],
    },
  ],
  gaps: [],
  metrics: {
    rounds: 2,
    actions: 6,
    evidenceItems: 2,
    commentEvidenceItems: 2,
    profiles: 2,
    controversies: 0,
    gaps: 0,
  },
  updatedAt: new Date().toISOString(),
  appliedEventIds: ['ev_gz_1', 'ev_gz_2'],
}

export function createDynamicProjection(query: string, sessionId: string): UserResearchProjectionV1 {
  const shopName = query.includes('面') ? '建设路老面馆' : query.includes('鸡') ? '建设路钵钵鸡老店' : '建设路地道美食'
  return {
    schemaVersion: USER_RESEARCH_PROJECTION_SCHEMA_VERSION,
    sessionId,
    taskId: `task_${Date.now()}`,
    turnId: 1,
    runId: `run_${Date.now()}`,
    revision: 1,
    lastSequence: 4,
    status: 'succeeded',
    phase: 'completed',
    summary: `已为你深入调研小红书与大众点评真实食客评价。针对您的需求：“${query}”：
严格筛选出 2 家建设路商圈高分街坊老店，用料扎实、口味地道、性价比高：
1. **${shopName}（老字号）**：每日现调红油甜酱，手工甜水面筋道爽滑，人均仅 25 元；
2. **蓉城老味道钵钵鸡**：红油与藤椒双拼，本地学生与街坊夜宵首选，荤素自选，避坑提示：饭点需稍微排队。`,
    intent: {
      objective: query,
      location: '建设路',
      constraints: ['地道风味', '高性价比'],
      exclusions: [],
    },
    plan: [
      {
        stepId: 'step_dyn_1',
        label: '意图拆解与商圈偏好建模',
        status: 'succeeded',
        detail: `解析需求：“${query}”，圈定目标周边500米范围`,
      },
      {
        stepId: 'step_dyn_2',
        label: '穿透小红书食客笔记与真实晒单',
        status: 'succeeded',
        detail: '调取真实笔记 64 篇，剔除商业推广文',
      },
      {
        stepId: 'step_dyn_3',
        label: '大众点评 POI 实体数据校验',
        status: 'succeeded',
        detail: '核对营业时间、人均消费与招牌菜排名',
      },
      {
        stepId: 'step_dyn_4',
        label: '综合比对与避坑结论输出',
        status: 'succeeded',
        detail: '生成针对性研判总结与候选商户档案',
      },
    ],
    recommendations: [
      {
        recommendationId: `rec_dyn_1_${Date.now()}`,
        title: `${shopName}（老字号）`,
        summary: '建设路开了十几年的传统老铺，红油甜酱比例精准，手工面条根根筋道，街坊排队必吃。',
        rank: 1,
        confidence: 0.93,
        profileRef: `prof_dyn_1`,
        highlights: ['秘制红油甜水酱', '现揉手工面筋道', '人均20元吃到撑'],
        warnings: ['店铺面积小，多为拼桌', '酱汁偏甜辣，建议充分拌匀'],
        evidenceRefs: [`ev_dyn_1`],
        controversyRefs: [],
      },
      {
        recommendationId: `rec_dyn_2_${Date.now()}`,
        title: '蓉城老味道钵钵鸡',
        summary: '红油香辣、藤椒鲜麻，荤素串串种类超60种，现选现泡，入味透彻。',
        rank: 2,
        confidence: 0.89,
        profileRef: `prof_dyn_2`,
        highlights: ['正宗乐山红油配方', '藤椒清爽麻舌', '牛肉串串鲜嫩'],
        warnings: ['晚上8点后部分热销菜品可能售罄', '竹签称重需注意核对'],
        evidenceRefs: [`ev_dyn_2`],
        controversyRefs: [],
      },
    ],
    evidence: [
      {
        evidenceId: `ev_dyn_1`,
        source: 'xhs_note',
        title: '建设路老饕私藏小吃',
        excerpt: '这家甜水面酱汁挂得极厚，微甜微辣还有花生碎，面条粗粗的有嚼头，比宽窄巷子那些商业街强太多！',
        stance: 'positive',
        confidence: 0.95,
        capturedAt: new Date().toISOString(),
        noteRef: 'xhs_dyn_101',
      },
      {
        evidenceId: `ev_dyn_2`,
        source: 'dianping_review',
        title: '开了十年的老牌钵钵鸡',
        excerpt: '红油特别香，芝麻撒得很足。鸡爪去骨彻底，贡菜又脆又入味，配一碗鸡汤饭简直绝了。',
        stance: 'positive',
        confidence: 0.90,
        capturedAt: new Date().toISOString(),
        commentRef: 'dp_dyn_202',
      },
    ],
    controversies: [
      {
        controversyId: `ct_dyn_1`,
        topic: '甜水面甜辣配比偏好',
        summary: '本地食客普遍认可浓郁复合味，部分外地游客反映甜味略重。',
        status: 'resolved',
        sides: [
          {
            sideId: 'sd_1',
            label: '偏好传统复合味',
            summary: '正宗成都甜水面就是酱油、红油与复制酱油的黄金甜辣平衡。',
            evidenceRefs: [`ev_dyn_1`],
          },
          {
            sideId: 'sd_2',
            label: '初尝游客建议',
            summary: '初次品尝可让店家少放些复制酱油，多加蒜水与辣椒油。',
            evidenceRefs: [],
          },
        ],
      },
    ],
    profiles: [
      {
        profileId: 'prof_dyn_1',
        name: `${shopName}（老字号）`,
        rating: 4.6,
        reviewCount: 920,
        averagePrice: 24,
        address: '成都市成华区建设路东二段18号附6号',
        openingHours: '周一至周日 10:30-21:30',
        category: '传统川味小吃',
        tags: ['建设路小吃榜', '老字号', '甜水面'],
        recommendedDishes: ['传统甜水面', '钟水饺', '红油抄手', '凉糕'],
      },
      {
        profileId: 'prof_dyn_2',
        name: '蓉城老味道钵钵鸡',
        rating: 4.5,
        reviewCount: 1140,
        averagePrice: 42,
        address: '成都市成华区建设巷11号',
        openingHours: '周一至周日 11:00-01:00',
        category: '特色乐山钵钵鸡',
        tags: ['夜宵热门', '红油钵钵鸡', '藤椒'],
        recommendedDishes: ['红油去骨鸭掌', '麻辣牛肉', '藤椒贡菜', '鸡汤饭'],
      },
    ],
    gaps: [],
    metrics: {
      rounds: 2,
      actions: 6,
      evidenceItems: 2,
      commentEvidenceItems: 2,
      profiles: 2,
      controversies: 1,
      gaps: 0,
    },
    updatedAt: new Date().toISOString(),
    appliedEventIds: [`ev_dyn_1`, `ev_dyn_2`],
  }
}
